config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :sessions, only: [:index, :show]
  resources :cinemas, only: [:index, :show]
  resources :sales

  resources :payments, only: [:create, :show]

  post "/payments/refresh", to: "payments#refresh_value"
  get "/payment/:sale_id", to: "payments#payment", as: :payment_path
  get "/history", to: "home#history", as: :history

  #devise_for :users
  root "home#index"

  resources :movies, only: [:index, :show]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cinema.rb
class Cinema < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :sessions

  scope :most_watched, -> { all.sort_by {|movie| movie.highest }.reverse }

  def highest
    self.sessions.map {|session| session.sales.count}.sum
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  validates_uniqueness_of :sale_id

  belongs_to :sale
  enum payment_method: [:debit, :credit, :cash]

  after_initialize :set_default_payment_method, :if => :new_record?

  def set_default_payment_method
    self.payment_method ||= :cash
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :sessions
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :session

  has_many :sale_seats
  has_many :seats, through: :sale_seats

  has_one :payment
  # has_many :payments
  validate :validate_seats_length
  # validates_length_of :seats, ]

  def validate_seats_length
    if self.seat_ids.size > 4
      self.errors.add(:seat_ids, "Número máximo de ingressos é 4")
    end
  end
end

app/models/sale_seat.rb
class SaleSeat < ApplicationRecord
  belongs_to :sale
  belongs_to :seat
end

app/models/seat.rb
class Seat < ApplicationRecord

  has_many :session_seats
  has_many :sessions, through: :session_seats

  has_many :sale_seats
  has_many :sales, through: :sale_seats

  def name
    "#{self.row}#{self.armchair}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :session_seats
  has_many :seats, through: :session_seats
  has_one :ticket
  has_many :sales
  has_one :room
  def start_time_br
    self.start_time.strftime("%H:%M")
  end
end

app/models/session_seat.rb
class SessionSeat < ApplicationRecord
  belongs_to :seat
  belongs_to :session
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:client, :admin, :student]

  after_initialize :set_default_role, :if => :new_record?
  has_many :sales
  def set_default_role
    self.role ||= :client
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    # before_action :authenticate_user!
    def index
      @movies = Movie.all
      @movies_watched = Movie.most_watched
    end

    def history
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :age_rating)
    end

    # Use in nested url case
    # def set_company
    #   @cinema = Cinema.find(params[:cinema_id])
    # rescue ActiveRecord::RecordNotFound
    #   head :not_found
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to(text, path, options={})
    super(text, path, options) unless options[:admin] and !current_user.nil? and !current_user.admin?
  end

  def button_to(text, path, options={})
    super(text, path, options) unless options[:admin] and !current_user.nil? and !current_user.admin?
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :movie_genre, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :age_rating %>
    <%= form.number_field :age_rating, id: :movie_age_rating, min: 0, max: 18, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Age rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.age_rating %></td>
        <td><%= button_to 'Show', movie, method: :get, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<main class="ptb100">
  <div class="container">

    <!-- Start of Movie List -->
    <div class="row">
      <!-- Movie List Item -->
      <% @movie.sessions.each do |session| %>
        <div class="col-md-12 col-sm-12">
          <div class="movie-list-1 mb30">
            <div class="listing-container">

              <!-- Movie List Image -->
              <div class="listing-image">

                <!-- Play Button -->
                <div class="play-btn">
                  <a href="https://www.youtube.com/watch?v=Q0CbN8sfihY" class="play-video">
                    <i class="fa fa-play"></i>
                  </a>
                </div>

                <!-- Buttons -->
                <div class="buttons">
                  <a href="#" data-original-title="Rate" data-toggle="tooltip" data-placement="bottom">
                    <i class="icon-heart"></i>
                  </a>

                  <a href="#" data-original-title="Share" data-toggle="tooltip" data-placement="bottom">
                    <i class="icon-share"></i>
                  </a>
                </div>

                <!-- Rating -->
                <div class="stars">
                  <div class="rating">
                    <strong>
                      Início da sessão às <%= session.start_time_br %> h
                    </strong>
                  </div>
                </div>

                <!-- Image -->
                <img src="assets/images/posters/poster-1.jpg" alt="">
              </div>

              <!-- Movie List Content -->
              <div class="listing-content">
                <div class="inner">
                  <h2 class="title"><%= @movie.title %></h2>

                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>


                  <%= link_to 'Comprar ingresso', session, method: :get, class: "btn btn-main btn-effect" %>
                </div>
              </div>

            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!-- End of Movie List -->

  </div>
</main>