config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :sessions, only: [:index, :show]
  resources :cinemas, only: [:index, :show]
  resources :sales

  resources :payments, only: [:create, :show]

  post "/payments/refresh", to: "payments#refresh_value"
  get "/payment/:sale_id", to: "payments#payment", as: :payment_path
  get "/history", to: "home#history", as: :history

  #devise_for :users
  root "home#index"

  resources :movies, only: [:index, :show]
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cinema.rb
class Cinema < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :sessions

  scope :most_watched, -> { all.sort_by {|movie| movie.highest }.reverse }

  def highest
    self.sessions.map {|session| session.sales.count}.sum
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  validates_uniqueness_of :sale_id

  belongs_to :sale
  enum payment_method: [:debit, :credit, :cash]

  after_initialize :set_default_payment_method, :if => :new_record?

  def set_default_payment_method
    self.payment_method ||= :cash
  end

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :sessions
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :session

  has_many :sale_seats
  has_many :seats, through: :sale_seats

  has_one :payment
  # has_many :payments
  validate :validate_seats_length
  # validates_length_of :seats, ]

  def validate_seats_length
    if self.seat_ids.size > 4
      self.errors.add(:seat_ids, "Número máximo de ingressos é 4")
    end
  end
end

app/models/sale_seat.rb
class SaleSeat < ApplicationRecord
  belongs_to :sale
  belongs_to :seat
end

app/models/seat.rb
class Seat < ApplicationRecord

  has_many :session_seats
  has_many :sessions, through: :session_seats

  has_many :sale_seats
  has_many :sales, through: :sale_seats

  def name
    "#{self.row}#{self.armchair}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :session_seats
  has_many :seats, through: :session_seats
  has_one :ticket
  has_many :sales
  has_one :room
  def start_time_br
    self.start_time.strftime("%H:%M")
  end
end

app/models/session_seat.rb
class SessionSeat < ApplicationRecord
  belongs_to :seat
  belongs_to :session
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :session
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:client, :admin, :student]

  after_initialize :set_default_role, :if => :new_record?
  has_many :sales
  def set_default_role
    self.role ||= :client
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to(text, path, options={})
    super(text, path, options) unless options[:admin] and !current_user.nil? and !current_user.admin?
  end

  def button_to(text, path, options={})
    super(text, path, options) unless options[:admin] and !current_user.nil? and !current_user.admin?
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_footer.html.erb
        <!-- =============== START OF FOOTER =============== -->
        <footer class="footer1 bg-dark">

            <!-- ===== START OF FOOTER WIDGET AREA ===== -->
            <div class="footer-widget-area ptb100">
                <div class="container">
                    <div class="row">

                        <!-- Start of Widget 1 -->
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="widget widget-about">

                                <!-- INSERT YOUR LOGO HERE -->
                                <%= image_tag "logo.svg", alt: "Logo", width: "150", class: "logo" %>
                                <%= image_tag "logo-white.svg", alt: "White logo", width: "150", class: "logo-white" %>
                                <p class="nomargin">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, ducimus, atque. Praesentium suscipit provident explicabo dignissimos nostrum numquam deserunt earum accusantium et fugit.</p>
                            </div>
                        </div>
                        <!-- End of Widget 1 -->

                        <!-- Start of Widget 2 -->
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="widget widget-links">
                            </div>
                        </div>
                        <!-- End of Widget 2 -->

                        <!-- Start of Widget 3 -->
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="widget widget-blog">
                            </div>
                        </div>
                        <!-- End of Widget 3 -->

                        <!-- Start of Widget 4 -->
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="widget widget-social">
                                <h4 class="widget-title">follow us</h4>

                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, ducimus, atque.</p>

                                <!-- Start of Social Buttons -->
                                <ul class="social-btns">
                                    <!-- Social Media -->
                                    <li>
                                        <a href="#" class="social-btn-roll facebook">
                                            <div class="social-btn-roll-icons">
                                                <i class="social-btn-roll-icon fa fa-facebook"></i>
                                                <i class="social-btn-roll-icon fa fa-facebook"></i>
                                            </div>
                                        </a>
                                    </li>

                                    <!-- Social Media -->
                                    <li>
                                        <a href="#" class="social-btn-roll twitter">
                                            <div class="social-btn-roll-icons">
                                                <i class="social-btn-roll-icon fa fa-twitter"></i>
                                                <i class="social-btn-roll-icon fa fa-twitter"></i>
                                            </div>
                                        </a>
                                    </li>

                                    <!-- Social Media -->
                                    <li>
                                        <a href="#" class="social-btn-roll google-plus">
                                            <div class="social-btn-roll-icons">
                                                <i class="social-btn-roll-icon fa fa-google-plus"></i>
                                                <i class="social-btn-roll-icon fa fa-google-plus"></i>
                                            </div>
                                        </a>
                                    </li>

                                    <!-- Social Media -->
                                    <li>
                                        <a href="#" class="social-btn-roll instagram">
                                            <div class="social-btn-roll-icons">
                                                <i class="social-btn-roll-icon fa fa-instagram"></i>
                                                <i class="social-btn-roll-icon fa fa-instagram"></i>
                                            </div>
                                        </a>
                                    </li>
                                </ul>
                                <!-- End of Social Buttons -->

                            </div>
                        </div>
                        <!-- End of Widget 4 -->

                    </div>
                </div>
            </div>
            <!-- ===== END OF FOOTER WIDGET AREA ===== -->


            <!-- ===== START OF FOOTER COPYRIGHT AREA ===== -->
            <div class="footer-copyright-area ptb30">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="d-flex">
                                <div class="links">
                                    <ul class="list-inline">
                                        <li class="list-inline-item"><a href="#">Privacy & Cookies</a></li>
                                        <li class="list-inline-item"><a href="#">Terms & Conditions</a></li>
                                        <li class="list-inline-item"><a href="#">Legal Disclaimer</a></li>
                                        <li class="list-inline-item"><a href="#">Community</a></li>
                                    </ul>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ===== END OF FOOTER COPYRIGHT AREA ===== -->

        </footer>
        <!-- =============== END OF FOOTER =============== -->

app/views/layouts/_login_and_signup.html.erb
<div id="login-register-popup" class="small-dialog zoom-anim-dialog mfp-hide">

    <!-- ===== Start of Signin wrapper ===== -->
    <div class="signin-wrapper">
        <div class="small-dialog-headline">
            <h4 class="text-center">Sign in</h4>
        </div>


        <div class="small-dialog-content">
            <%= render template: "users/sessions/new" %>
            <!-- Start of Login form -->
            <!-- <form id="cariera_login" method="post">
                <p class="status"></p>

                <div class="form-group">
                    <label for="username">Username or Email *</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Your Username or Email *" />
                </div>

                <div class="form-group">
                    <label for="password">Password *</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Your Password *" />
                </div>

                <div class="form-group">
                    <div class="checkbox pad-bottom-10">
                        <input id="check1" type="checkbox" name="remember" value="yes">
                        <label for="check1">Keep me signed in</label>
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" value="Sign in" class="btn btn-main btn-effect nomargin" />
                </div>
            </form> -->
            <!-- End of Login form -->

            <div class="bottom-links">
                <span>
                    Não é um membro?
                    <a  class="signUpClick">Sign up</a>
                </span>
            </div>
        </div>

    </div>
    <!-- ===== End of Signin wrapper ===== -->



    <!-- ===== Start of Signup wrapper ===== -->
    <div class="signup-wrapper">
        <div class="small-dialog-headline">
            <h4 class="text-center">Sign Up</h4>
        </div>

        <div class="small-dialog-content">
          <%= render template: "users/registrations/new" %>
            <!-- Start of Registration form -->
            <!-- <form id="cariera_registration" action="#" method="POST">
                <p class="status"></p>

                <div class="form-group">
                    <label for="movify_user_login">Username</label>
                    <input name="movify_user_login" id="movify_user_login" class="form-control" type="text"/>
                </div>

                <div class="form-group">
                    <label for="movify_user_email">Email</label>
                    <input name="movify_user_email" id="movify_user_email" class="form-control" type="email"/>
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input name="movify_user_pass" id="movify_password" class="form-control" type="password"/>
                </div>

                <div class="form-group">
                    <input type="submit" class="btn btn-main btn-effect nomargin" value="Register"/>
                </div>
            </form> -->
            <!-- End of Registration form -->

            <div class="bottom-links">
                <span>
                    Já tem uma conta?
                    <a class="signInClick">Sign in</a>
                </span>

                <!-- <a class="forgetPasswordClick pull-right">Forgot Password</a> -->
            </div>

        </div> <!-- .small-dialog-content -->

    </div>
    <!-- ===== End of Signup wrapper ===== -->

app/views/layouts/_most_ranked.html.erb
<!-- =============== START OF UPCOMING MOVIES SECTION =============== -->
<section class="upcoming-movies parallax ptb100" data-background="assets/images/posters/movie-collection.jpg" data-color="#3e4555" data-color-opacity="0.95" >
    <div class="container">

        <!-- Start of row -->
        <div class="row justify-content-center">
            <div class="col-md-7 text-center">
                <h2 class="title text-white">Confia nosso ranking</h2>
            </div>
        </div>
        <!-- End of row -->

=

    </div>
</section>
<!-- =============== END OF UPCOMING MOVIES SECTION =============== -->




<!-- =============== START OF LATEST TV SHOW SECTION =============== -->
<section class="latest-tvshows ptb100">
    <div class="container">

        <!-- Start of row -->
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <h2 class="title">Mais assistidos</h2>
            </div>

        </div>
        <!-- End of row -->


        <!-- Start of Latest Movies Slider -->
        <div class="owl-carousel latest-tvshows-slider mt20">

          <% @movies_watched.each do |moviee| %>
            <!-- === Start of Sliding Item 1 === -->
            <div class="item">
              <!-- Start of Movie Box -->
              <div class="movie-box-1">

                <!-- Start of Poster -->
                <div class="poster">
                  <img src="assets/images/posters/poster-5.jpg" alt="">
                </div>
                <!-- End of Poster -->

                <!-- Start of Buttons -->
                <div class="buttons">
                  <a href="https://www.youtube.com/watch?v=Q0CbN8sfihY" class="play-video">
                    <i class="fa fa-play"></i>
                  </a>
                </div>
                <!-- End of Buttons -->

                <!-- Start of Movie Details -->
                <div class="movie-details">
                  <h4 class="movie-title">
                    <a href="#"><%= moviee.title %></a>
                  </h4>
                  <span class="released"><%= moviee.highest %> vezes</span>
                </div>
                <!-- End of Movie Details -->

                <!-- Start of Rating -->
                <div class="stars">
                  <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star-half-o"></i>
                  </div>
                  <span><%= (rand * 10).round(1) %> / 10</span>
                </div>
                <!-- End of Rating -->

              </div>
              <!-- End of Movie Box -->
            </div>
            <!-- === End of Sliding Item 1 === -->
          <% end %>

        </div>
        <!-- End of Latest Movies Slider -->

    </div>
</section>
<!-- =============== END OF LATEST TV SHOW SECTION =============== -->

app/views/layouts/_movies.html.erb
<!-- =============== START OF LATEST MOVIES SECTION =============== -->
<section class="latest-movies ptb100">
  <div class="container">

    <!-- Start of row -->
    <div class="row">
      <div class="col-md-8">
        <h2 class="title">Últimos filmes</h2>
      </div>
    </div>
    <!-- End of row -->

    <!-- Start of Latest Movies Slider -->
    <div class="owl-carousel latest-movies-slider mt20">

      <% @movies.each do |movie| %>
        <!-- === Start of Sliding Item 1 === -->
        <div class="item">
          <!-- Start of Movie Box -->
          <div class="movie-box-1">

            <!-- Start of Poster -->
            <div class="poster">
              <img src="assets/images/posters/poster-1.jpg" alt="">
            </div>
            <!-- End of Poster -->

            <!-- Start of Buttons -->
            <div class="buttons">
              <a href="https://www.youtube.com/watch?/v=Q0CbN8sfihY" class="play-video">
                <i class="fa fa-play"></i>
              </a>
            </div>
            <!-- End of Buttons -->

            <!-- Start of Movie Details -->
            <div class="movie-details">
              <h4 class="movie-title">
                <%= link_to movie.title, movie %>
              </h4>
              <span class="released"><%= movie.created_at.strftime("%d/%m/%Y") %></span>
            </div>
            <!-- End of Movie Details -->

            <!-- Start of Rating -->
            <div class="stars">
              <div class="rating">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star-o"></i>
              </div>
              <span><%= (rand * 10).round(1) %>
                / 10</span>
            </div>
            <!-- End of Rating -->

          </div>
          <!-- End of Movie Box -->
        </div>
        <!-- === End of Sliding Item 1 === -->
      <% end %>
    </div>
    <!-- End of Latest Movies Slider -->

  </div>
</section>
<!-- =============== END OF LATEST MOVIES SECTION =============== -->

app/views/layouts/_navbar.html.erb
<!-- =============== START OF HEADER NAVIGATION =============== -->
<!-- Insert the class "sticky" in the header if you want a sticky header -->
<header class="header header-fixed header-transparent text-white">
    <div class="container-fluid">

        <!-- ====== Start of Navbar ====== -->
        <nav class="navbar navbar-expand-lg">

            <%= link_to root_url, class: "navbar-brand" do %>
              <%= image_tag "logo.svg", alt: "Logo", width: "150", class: "logo" %>
              <%= image_tag "logo-white.svg", alt: "White logo", width: "150", class: "logo-white" %>
            <% end %>

            <button id="mobile-nav-toggler" class="hamburger hamburger--collapse" type="button">
               <span class="hamburger-box">
                  <span class="hamburger-inner"></span>
               </span>
            </button>

            <!-- ====== Start of #main-nav ====== -->
            <div class="navbar-collapse" id="main-nav">

                <!-- ====== Start of Main Menu ====== -->
                <ul class="navbar-nav mx-auto" id="main-menu">
                    <!-- Menu Item -->
                    <li class="nav-item">
                        <%= link_to "Home", root_url, class: "nav-link" %>
                    </li>

                    <!-- Menu Item -->
                    <li class="nav-item">
                        <a class="nav-link" href="#">Blog</a>
                    </li>

                    <!-- Menu Item -->
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contate-nos</a>
                    </li>

                    <!-- Menu Item -->
                    <li class="nav-item">
                      <% if user_signed_in? %>
                        <%= link_to "Histórico", history_path, class: "nav-link" %>
                      <% end %>
                        <!-- <a class="nav-link" href="#">Histórico de compras</a> -->
                    </li>

                </ul>
                <!-- ====== End of Main Menu ====== -->


                <!-- ====== Start of Extra Nav ====== -->
                <ul class="navbar-nav extra-nav">

                    <!-- Menu Item -->
                    <li class="nav-item">
                        <a class="nav-link toggle-search" href="#">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>

                    <!-- Menu Item -->
                    <li class="nav-item notification-wrapper">
                        <a class="nav-link notification" href="#">
                            <i class="fa fa-globe"></i>
                            <span class="notification-count">2</span>
                        </a>
                    </li>

                    <!-- Menu Item -->
                    <% unless user_signed_in? %>
                      <li class="nav-item m-auto">
                          <a href="#login-register-popup" class="btn btn-main btn-effect login-btn popup-with-zoom-anim">
                              <i class="icon-user"></i>login
                          </a>
                      </li>
                    <% end %>

                    <% if user_signed_in? %>
                    <li class="nav-item">
                      <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"btn btn-main btn-effect login-btn popup-with-zoom-anim" %>
                    </li>
                    <% end %>

                </ul>
                <!-- ====== End of Extra Nav ====== -->

            </div>
            <!-- ====== End of #main-nav ====== -->
        </nav>
        <!-- ====== End of Navbar ====== -->

    </div>
</header>
<!-- =============== END OF HEADER NAVIGATION =============== -->

app/views/layouts/_notify.html.erb
<script type="text/javascript">
$(document).ready(function() {
  <% unless notice.nil? %>
    $.notify({
      icon: "fa fa-thumbs-up",
      message: "<%= notice %>"
    }, {
      type: "info",
      allow_demiss: true,
      offset: {
        x: 50,
        y: 100
      },
      animate: {
        enter: 'animated fadeInRight',
        exit: 'animated fadeOutLeft'
      }
    });
  <% end %>
  <% unless alert.nil? %>
    $.notify({
      icon: "fa fa-exclamation-triangle",
      message: "<%= alert %>"
    }, {
      type: "danger",
      allow_demiss: true,
      offset: {
        x: 50,
        y: 100
      },
      animate: {
        enter: 'animated fadeInRight',
        exit: 'animated fadeOutLeft'
      }
    });
  <% end %>
});
</script>

app/views/layouts/_preloader.html.erb
    <!-- =============== START OF PRELOADER =============== -->
<div class="loading">
    <div class="loading-inner">
        <div class="loading-effect">
            <div class="object"></div>
        </div>
    </div>
</div>
<!-- =============== END OF PRELOADER =============== -->

app/views/layouts/_responsive_nav.html.erb
<!-- =============== START OF RESPONSIVE - MAIN NAV =============== -->
<nav id="main-mobile-nav"></nav>
<!-- =============== END OF RESPONSIVE - MAIN NAV =============== -->

app/views/layouts/_resto.html.erb
        <!-- =============== END OF COUNTER SECTION =============== -->
        <section class="counter bg-main-gradient ptb50 text-center">
            <div class="container">
                <div class="row">

                    <!-- 1st Count up item -->
                    <div class="col-md-4 col-sm-12">
                        <span class="counter-item" data-from="0" data-to="964">0</span>
                        <h4>Filmes</h4>
                    </div>

                    <!-- 2nd Count up item -->
                    <div class="col-md-4 col-sm-12">
                        <span class="counter-item" data-from="0" data-to="743">0</span>
                        <h4>Programas de TV</h4>
                    </div>

                    <!-- 3rd Count up item -->
                    <div class="col-md-4 col-sm-12">
                        <span class="counter-item" data-from="0" data-to="1207">0</span>
                        <h4>Usuários</h4>
                    </div>

                </div>
            </div>
        </section>
        <!-- =============== END OF COUNTER SECTION =============== -->

app/views/layouts/_slider.html.erb
<!-- =============== START OF SLIDER REVOLUTION SECTION =============== -->
<section id="slider" class="full-slider">
  <div class="rev-slider-wrapper fullscreen-container overlay-gradient">
    <div id="fullscreen-slider" class="rev_slider fullscreenbanner" style="display:none" data-version="5.4.1">
      <ul>

        <!-- ===== SLIDE NR. 1 ===== -->
        <li data-transition="fade">
          <!-- MAIN IMAGE -->
          <img src="assets/images/slider/slider1.jpg" alt="Image" title="slider-bg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina="">
          <!-- LAYER NR. 1 -->
          <div
            class="tp-caption tp-resizeme"
            data-x="center"
            data-hoffset=""
            data-y="middle"
            data-voffset="['-30','-30','-30','-30']"
            data-responsive_offset="on"
            data-fontsize="['60','50','40','30']"
            data-lineheight="['60','50','40','30']"
            data-whitespace="nowrap"
            data-frames='[{"delay":1000,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
            style="z-index: 5; color: #fff; font-weight: 900;">IMAX 5D PLUS PLUS
          </div>
        </li>

        <!-- ===== SLIDE NR. 2 ===== -->
        <li data-transition="fade" data-slotamount="7" data-easein="default" data-easeout="default" data-masterspeed="2000">
          <!-- MAIN IMAGE -->
          <img src="assets/images/slider/slider2.jpg" alt="Image" title="slider-bg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="10" class="rev-slidebg" data-no-retina="">
          <!-- LAYER NR. 1 -->
          <div
            class="tp-caption tp-resizeme"
            data-x="center"
            data-hoffset=""
            data-y="middle"
            data-voffset="['-30','-30','-30','-30']"
            data-responsive_offset="on"
            data-fontsize="['60','50','40','30']"
            data-lineheight="['60','50','40','30']"
            data-whitespace="nowrap"
            data-frames='[{"delay":1000,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
            style="z-index: 5; color: #fff; font-weight: 900;">RESOLUÇÃO ULTRA HD
          </div>
        </li>

        <!-- ===== SLIDE NR. 3 ===== -->
        <li data-transition="fade" data-slotamount="7" data-easein="default" data-easeout="default" data-masterspeed="2000">
          <!-- MAIN IMAGE -->
          <img src="assets/images/slider/slider3.jpg" alt="Image" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="3" class="rev-slidebg" data-no-retina="data-no-retina">
          <!-- LAYER NR. 1 -->
          <div
            class="tp-caption tp-resizeme"
            data-x="center"
            data-hoffset=""
            data-y="middle"
            data-voffset="['-30','-30','-30','-30']"
            data-responsive_offset="on"
            data-fontsize="['60','50','40','30']"
            data-lineheight="['60','50','40','30']"
            data-whitespace="nowrap"
            data-frames='[{"delay":1000,"speed":2000,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
            style="z-index: 5; color: #fff; font-weight: 900;">ÚLTIMOS FILMES E SÉRIES
          </div>
        </li>

      </ul>
    </div>
  </div>
  <!-- ===== END OF REV SLIDER WRAPPER ===== -->
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Popcorn Land</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "favicon" %>
    <!-- ===== Google Fonts ===== -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/preloader" %>
    <%= render "layouts/responsive_nav" %>
    <div class="wrapper">
        <%= render "layouts/navbar" %>
        <%= render "layouts/slider" %>
        <%= yield %>
        <%= render "layouts/footer" %>

    </div>
    <%= render "layouts/login_and_signup" %>
    <%= render "layouts/notify" %>
  </body>
</html>